services:
  - type: web
    name: aps-libravault
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        sync: false